#!/usr/bin/env python3
"""Build the blob in ../sr2-patcher.py from asm/, or check that it still matches.

    python3 asm/build.py            # assemble and write
    python3 asm/build.py --check    # verify only, writes nothing

sr2-patcher.py carries the assembled bytes because it ships as one file that
runs from a fresh checkout with nothing installed. Never edit the hex by
hand; this overwrites it. The placeholders the patcher fills at apply time
are listed in MAGICS, and each must appear in the blob at least once.
"""
import os
import re
import struct
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TARGET = os.path.join(ROOT, 'sr2-patcher.py')

BLOBS = [('MUSIC_BLOB', 'music.asm')]

MAGICS = {
    'MAGIC_ORIGENTRY': 0xE1E1E1E1,
    'MAGIC_IATMCI': 0xE2E2E2E2,
    'MAGIC_LOADLIB': 0xE3E3E3E3,
    'MAGIC_GETPROC': 0xE4E4E4E4,
    'MAGIC_GETMODFN': 0xE5E5E5E5,
}

BEGIN = '# --- GENERATED by asm/build.py: BEGIN (do not edit) ---\n'
END = '# --- GENERATED by asm/build.py: END ---\n'


def assemble(src):
    with tempfile.TemporaryDirectory() as tmp:
        out = os.path.join(tmp, 'blob.bin')
        subprocess.check_call(['nasm', '-f', 'bin', '-o', out, os.path.join(HERE, src)])
        with open(out, 'rb') as fh:
            return fh.read()


def hexblob(name, raw):
    text = raw.hex()
    lines = ["    '%s'\n" % text[i:i + 64] for i in range(0, len(text), 64)]
    return '%s = bytes.fromhex(\n%s)\n' % (name, ''.join(lines))


def generated():
    out = [BEGIN]
    for name, src in BLOBS:
        raw = assemble(src)
        for magic, value in MAGICS.items():
            if struct.pack('<I', value) not in raw:
                raise SystemExit('%s: %s does not occur in %s' % (src, magic, name))
        out.append(hexblob(name, raw))
    out.append('MUSIC_MAGICS = %r\n' % MAGICS)
    out.append(END)
    return ''.join(out)


def main(argv):
    check = '--check' in argv
    with open(TARGET, encoding='utf-8') as fh:
        text = fh.read()
    pattern = re.compile(re.escape(BEGIN) + '.*?' + re.escape(END), re.S)
    if not pattern.search(text):
        raise SystemExit('no GENERATED region in sr2-patcher.py')
    new = generated()
    if check:
        if pattern.search(text).group(0) == new:
            print('blobs match')
            return 0
        print('blobs differ: run asm/build.py')
        return 1
    text = pattern.sub(lambda _m: new, text)
    with open(TARGET, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(text)
    print('wrote %d blob(s) into sr2-patcher.py' % len(BLOBS))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
