#!/usr/bin/env python3
"""Build the blob in ../sr2-patcher.py from asm/, or check that it still matches.

    python3 asm/build.py            # assemble and write
    python3 asm/build.py --check    # verify only, writes nothing

sr2-patcher.py carries the assembled bytes because it ships as one file that
runs from a fresh checkout with nothing installed. Never edit the hex by
hand; this overwrites it. The placeholders the patcher fills at apply time
are listed in MAGICS; the music blob must hold each of MUSIC_MAGICS at
least once, and each exe stub each of its EXE_MAGICS exactly once.
"""
import os
import re
import struct
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TARGET = os.path.join(ROOT, 'sr2-patcher.py')

BLOBS = [('MUSIC_BLOB', 'music.asm', ()), ('ACTIVATE_BLOB', 'activate.asm', ()),
         ('RESTORE_BLOB', 'restore.asm', ()), ('TEXTCOLOR_BLOB', 'textcolor.asm', ()),
         ('BGROW_BLOB', 'bgrow.asm', ()), ('TITLEROW_BLOB', 'bgrow.asm', ('-DTITLE',)),
         ('FULLWIN_BLOB', 'fullwin.asm', ()), ('ALTENTER_BLOB', 'altenter.asm', ()),
         ('MIX_BLOB', 'mix.asm', ()), ('VOLTRACE_BLOB', 'voltrace.asm', ()),
         ('DEVICES_BLOB', 'devices.asm', ())]

MAGICS = {
    'MAGIC_ORIGENTRY': 0xE1E1E1E1,
    'MAGIC_IATMCI': 0xE2E2E2E2,
    'MAGIC_LOADLIB': 0xE3E3E3E3,
    'MAGIC_GETPROC': 0xE4E4E4E4,
    'MAGIC_GETMODFN': 0xE5E5E5E5,
}

# The exe stubs' placeholders, filled with absolute addresses from the
# build's row; the two IAT ones share their values with MAGICS.
EXE_MAGICS = {
    'GAMED3D': 0xEAEAEAEA,
    'RESUME': 0xEBEBEBEB,
    'HANDLER': 0xECECECEC,
    'LOADLIB': 0xE3E3E3E3,
    'GETPROC': 0xE4E4E4E4,
    'HWND': 0xEDEDEDED,
    'WIDTH': 0xEEEEEEEE,
    'HEIGHT': 0xEFEFEFEF,
    'BITCOUNT': 0xF1F1F1F1,
    'SETTEXTCOLOR': 0xF2F2F2F2,
}
EXE_BLOB_MAGICS = {
    'ACTIVATE_BLOB': ('GAMED3D', 'RESUME'),
    'ALTENTER_BLOB': ('HANDLER', 'LOADLIB', 'GETPROC', 'HWND', 'WIDTH', 'HEIGHT'),
    'BGROW_BLOB': ('BITCOUNT',),
    'TEXTCOLOR_BLOB': ('SETTEXTCOLOR',),
    'VOLTRACE_BLOB': ('LOADLIB', 'GETPROC'),
}

# devices.asm's placeholders: RVAs in Options.dll from the build's row,
# and the blob's own RVA and its data's, from the patcher.
DEVICES_MAGICS = {
    'SELFRVA': 0xD1D1D1D1,
    'EPILOGUE': 0xD2D2D2D2,
    'BINDPAGE': 0xD3D3D3D3,
    'DRAW': 0xD4D4D4D4,
    'PLAYSOUND': 0xD5D5D5D5,
    'INPUT': 0xD6D6D6D6,
    'SOUNDOBJ': 0xD7D7D7D7,
    'HANDLES': 0xD8D8D8D8,
    'PAGEHDR': 0xD9D9D9D9,
    'DRAWLIST': 0xDADADADA,
    'TEXT': 0xDBDBDBDB,
    'GLYPHS': 0xDCDCDCDC,
    'ROWS': 0xDDDDDDDD,
    'HINT': 0xDEDEDEDE,
}

# An exe stub's source must not name an exe address: every one moves
# between builds and belongs in the row. Comments may.
EXE_ADDRESS = re.compile(r'^[^;]*\b0x[4-6][0-9a-fA-F]{5}\b', re.M)

# fullwin.asm finds the image base from its own RVA, which the patcher
# fills in over this.
SELF_MAGIC = 0xE7E7E7E7

BEGIN = '# --- GENERATED by asm/build.py: BEGIN (do not edit) ---\n'
END = '# --- GENERATED by asm/build.py: END ---\n'


MIX_INC = os.path.join(HERE, 'mix.inc')
CURVE_INC = os.path.join(HERE, 'curve.inc')


def mix_constants():
    """The %defines of mix.inc, evaluated."""
    values = {}
    for line in open(MIX_INC):
        m = re.match(r'%define\s+(\w+)\s+([^;]+)', line)
        if m:
            values[m.group(1)] = int(eval(m.group(2).strip(), {}, values))
    return values


def curve_inc():
    """curve.inc: the CD music's waveOut amplitude per slider step, the
    mix's curve plus CD_DB, 0 off. Derived, since nasm cannot raise 10 to
    a power."""
    c = mix_constants()
    amps = [0] + [min(65535, round(65535 * 10 ** ((c['MIX_BOTTOM'] + c['MIX_STEP'] * s + c['CD_DB']) / 2000)))
                  for s in range(1, 10)]
    return ('; curve.inc - generated by build.py from mix.inc; do not edit.\n'
            '; The CD music per slider step: the mix curve plus CD_DB, as waveOut amplitudes, 0 off.\n'
            '%%define CD_CURVE %s\n'
            '%%define CD_FULL %d\n' % (', '.join(map(str, amps)), amps[9] | amps[9] << 16))


def assemble(src, defines=()):
    with tempfile.TemporaryDirectory() as tmp:
        out = os.path.join(tmp, 'blob.bin')
        subprocess.check_call(['nasm', '-f', 'bin', '-i', HERE + os.sep, *defines, '-o', out, os.path.join(HERE, src)])
        with open(out, 'rb') as fh:
            return fh.read()


def hexblob(name, raw):
    text = raw.hex()
    lines = ["    '%s'\n" % text[i:i + 64] for i in range(0, len(text), 64)]
    return '%s = bytes.fromhex(\n%s)\n' % (name, ''.join(lines))


def generated(check=False):
    curve = curve_inc()
    if check:
        if not os.path.isfile(CURVE_INC) or open(CURVE_INC).read() != curve:
            raise SystemExit('curve.inc is not what mix.inc gives: run asm/build.py')
    else:
        with open(CURVE_INC, 'w') as fh:
            fh.write(curve)
    out = [BEGIN]
    for name, src, defines in BLOBS:
        raw = assemble(src, defines)
        if name == 'FULLWIN_BLOB' and raw.count(struct.pack('<I', SELF_MAGIC)) != 1:
            raise SystemExit('%s: MAGIC_SELFRVA must occur exactly once' % src)
        if name == 'MUSIC_BLOB':
            for magic, value in MAGICS.items():
                if struct.pack('<I', value) not in raw:
                    raise SystemExit('%s: %s does not occur in %s' % (src, magic, name))
        elif name == 'DEVICES_BLOB':
            for magic, value in DEVICES_MAGICS.items():
                if struct.pack('<I', value) not in raw:
                    raise SystemExit('%s: %s does not occur in %s' % (src, magic, name))
        elif name != 'TITLEROW_BLOB':
            for magic, value in EXE_MAGICS.items():
                want = EXE_BLOB_MAGICS.get(name, ()).count(magic)
                if raw.count(struct.pack('<I', value)) != want:
                    raise SystemExit('%s: %s should occur %d time(s) in %s' % (src, magic, want, name))
            if name in EXE_BLOB_MAGICS:
                with open(os.path.join(HERE, src)) as fh:
                    hit = EXE_ADDRESS.search(fh.read())
                if hit:
                    raise SystemExit('%s: an exe address in the source (%s); put it in the row' % (src, hit.group(0).strip()))
        out.append(hexblob(name, raw))
    out.append('MUSIC_MAGICS = {\n%s}\n' % ''.join("    '%s': 0x%08X,\n" % kv for kv in MAGICS.items()))
    out.append('EXE_MAGICS = {\n%s}\n' % ''.join("    '%s': 0x%08X,\n" % kv for kv in EXE_MAGICS.items()))
    out.append('FULLWIN_MAGIC = 0x%08X\n' % SELF_MAGIC)
    out.append('DEVICES_MAGICS = {\n%s}\n' % ''.join("    '%s': 0x%08X,\n" % kv for kv in DEVICES_MAGICS.items()))
    out.append(END)
    return ''.join(out)


def main(argv):
    check = '--check' in argv
    with open(TARGET, encoding='utf-8') as fh:
        text = fh.read()
    pattern = re.compile(re.escape(BEGIN) + '.*?' + re.escape(END), re.S)
    if not pattern.search(text):
        raise SystemExit('no GENERATED region in sr2-patcher.py')
    new = generated(check)
    if check:
        if pattern.search(text).group(0) == new:
            print('blobs match')
            return 0
        print('blobs differ: run asm/build.py')
        return 1
    text = pattern.sub(lambda _m: new, text)
    with open(TARGET, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(text)
    print('wrote %d blob(s) into sr2-patcher.py' % len(BLOBS))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
