#!/usr/bin/env python3
"""Render the connection screen's labels and bake them into ../sr2-patcher.py,
or check that they still match.

    python3 tools/labels.py             # render and write
    python3 tools/labels.py --check     # verify only, writes nothing
    python3 tools/labels.py --show DIR  # also write the BMPs to DIR to look at

The stock buttons (BINDATA\\PROTOCOL\\CONNECT_*_{OFF,ON,ON2}.BMP, 218x32,
24-bit) are ITC Avant Garde Gothic Demi at 20 px cap height, letterspaced
and centred: OFF the lettering at 98/255, ON at full, ON2 with a glow.
URW Gothic Demi is that face's free clone (fonts-urw-base35), and the
sizes below reproduce the stock lettering to the pixel. The patcher
ships the three states of each label as zlib-compressed 8-bit masks and
composes the BMPs itself, so Pillow and the font are needed here only.
"""
import base64
import os
import re
import sys
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TARGET = os.path.join(ROOT, 'sr2-patcher.py')

# Which stock button file set carries which label: the exe draws these
# three slots as rows 0, 1 and 2.
LABELS = (('IPX', 'INTERNET'), ('TCPIP', 'DIRECT IP'), ('MODEM', 'LAN'))
STATES = ('OFF', 'ON', 'ON2')

FONTS = ('/usr/share/fonts/opentype/urw-base35/URWGothic-Demi.otf',    # Debian, Ubuntu
         '/usr/share/fonts/urw-base35/URWGothic-Demi.otf',             # Fedora
         '/usr/share/fonts/type1/urw-base35/URWGothic-Demi.t1')
SIZE = 27                       # 20 px cap height, 4 px stems
TRACK = 7                       # extra pixels between letters
W, H = 218, 32
TOP = 6                         # the lettering's top row
OFF_LEVEL = 98 / 255.0
GLOW_SIGMA, GLOW_GAIN = 2.4, 2.0    # fitted against the stock ON2 buttons

BEGIN = '# --- GENERATED by tools/labels.py: BEGIN (do not edit) ---\n'
END = '# --- GENERATED by tools/labels.py: END ---\n'


def font():
    """URW Gothic Demi from one of the known paths, else wherever
    fontconfig says it is."""
    import subprocess
    from PIL import ImageFont
    paths = list(FONTS)
    try:
        found = subprocess.run(['fc-match', '-f', '%{file}', 'URW Gothic:style=Demi'],
                               capture_output=True, text=True, timeout=10).stdout.strip()
        if found.endswith(('URWGothic-Demi.otf', 'URWGothic-Demi.t1', 'URWGothic-Demi.pfb')):
            paths.append(found)
    except (OSError, subprocess.SubprocessError):
        pass
    for path in paths:
        if os.path.isfile(path):
            return ImageFont.truetype(path, SIZE)
    raise SystemExit('URW Gothic Demi not found; install fonts-urw-base35 (Fedora: urw-base35-fonts)')


def mask(text):
    """The ON state: the text letterspaced, its ink centred, top at TOP."""
    from PIL import Image, ImageDraw
    fnt = font()
    big = Image.new('L', (W * 2, H * 2), 0)
    draw = ImageDraw.Draw(big)
    x = W / 2.0
    for ch in text:
        draw.text((x, H / 2.0), ch, font=fnt, fill=255)
        x += draw.textlength(ch, font=fnt) + (TRACK if ch != ' ' else TRACK * 0.6)
    box = big.getbbox()
    out = Image.new('L', (W, H), 0)
    out.paste(big, ((W - (box[2] - box[0])) // 2 - box[0], TOP - box[1]))
    return out


def states(on):
    from PIL import ImageChops, ImageFilter
    off = on.point(lambda v: int(v * OFF_LEVEL + 0.5))
    glow = on.filter(ImageFilter.GaussianBlur(GLOW_SIGMA)).point(lambda v: min(255, int(v * GLOW_GAIN)))
    return off, on, ImageChops.lighter(on, glow)


def render():
    out = {}
    for slot, text in LABELS:
        out[slot] = (text,) + tuple(im.tobytes() for im in states(mask(text)))
    return out


def generated(labels):
    lines = [BEGIN, '# The connection screen\'s labels: slot -> (text, OFF, ON, ON2), each a\n',
             '# zlib-compressed 218x32 8-bit mask; see tools/labels.py.\n', 'LOBBY_LABELS = {\n']
    for slot, (text, *masks) in labels.items():
        lines.append("    '%s': ('%s',\n" % (slot, text))
        for m in masks:
            b64 = base64.b64encode(zlib.compress(m, 9)).decode('ascii')
            chunks = ["'%s'" % b64[i:i + 96] for i in range(0, len(b64), 96)]
            lines.append('        ' + '\n        '.join(chunks) + ',\n')
        lines.append('    ),\n')
    lines.append('}\n')
    lines.append(END)
    return ''.join(lines)


# A font rasterises a little differently from one FreeType or font build
# to the next, so the check does not ask for the baked bytes: a rendering
# is the same lettering when, for every state, the mean difference is
# under MEAN_TOLERANCE of 255 and at most FAR_TOLERANCE of the pixels are
# more than FAR apart.
MEAN_TOLERANCE, FAR_TOLERANCE, FAR = 2.0, 0.03, 64


def carried(region):
    """The masks the script carries: the generated region run as Python."""
    ns = {}
    exec(region, ns)
    return {slot: (text,) + tuple(zlib.decompress(base64.b64decode(m)) for m in masks)
            for slot, (text, *masks) in ns['LOBBY_LABELS'].items()}


def compare(a, b):
    """The worst (mean difference, share of pixels FAR apart, where) over
    every slot and state of two label sets."""
    worst = (0.0, 0.0, '')
    for slot in LABELS:
        slot = slot[0]
        for i, state in enumerate(STATES):
            x, y = a[slot][1 + i], b[slot][1 + i]
            if len(x) != len(y):
                return (255.0, 1.0, '%s %s: sizes differ' % (slot, state))
            diffs = [abs(p - q) for p, q in zip(x, y)]
            mean, far = sum(diffs) / len(diffs), sum(d > FAR for d in diffs) / len(diffs)
            if (mean, far) > worst[:2]:
                worst = (mean, far, '%s %s' % (slot, state))
    return worst


def write_bmps(labels, folder):
    from PIL import Image
    os.makedirs(folder, exist_ok=True)
    for slot, (text, *masks) in labels.items():
        for state, m in zip(STATES, masks):
            im = Image.frombytes('L', (W, H), m).convert('RGB')
            im.save(os.path.join(folder, 'CONNECT_%s_%s.BMP' % (slot, state)))


def main(argv):
    check = '--check' in argv
    with open(TARGET, encoding='utf-8') as fh:
        text = fh.read()
    pattern = re.compile(re.escape(BEGIN) + '.*?' + re.escape(END), re.S)
    if not pattern.search(text):
        raise SystemExit('no labels region in sr2-patcher.py')
    try:
        labels = render()
    except (ImportError, SystemExit) as exc:
        if check:
            print('labels: skipped (%s)' % exc)
            return 77                   # what tools/check.py reads as a skip, not a pass
        raise
    if '--show' in argv:
        write_bmps(labels, argv[argv.index('--show') + 1])
    new = generated(labels)
    if check:
        baked = pattern.search(text).group(0)
        if baked == new:
            print('labels match')
            return 0
        worst = compare(carried(baked), labels)
        if worst[0] <= MEAN_TOLERANCE and worst[1] <= FAR_TOLERANCE:
            print('note: labels match within the rasteriser\'s tolerance: mean %.2f/255 off, %.1f%% of pixels far off at worst (%s)'
                  % (worst[0], worst[1] * 100, worst[2]))
            return 0
        print('labels differ: mean %.2f/255 off, %.1f%% of pixels far off (%s); run tools/labels.py on the machine the masks come from'
              % (worst[0], worst[1] * 100, worst[2]))
        return 1
    text = pattern.sub(lambda _m: new, text)
    with open(TARGET, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(text)
    print('wrote %d label(s) into sr2-patcher.py' % len(labels))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
