#!/usr/bin/env python3
"""Render the pad's prompts and bake them into ../sr2-patcher.py, or check
that they still match.

    python3 tools/prompts.py [GAMEDIR]            # render and write
    python3 tools/prompts.py --check              # verify only, writes nothing
    python3 tools/prompts.py --show DIR GAMEDIR   # also write PNGs to DIR to look at

The game's prompts are lettering in its texture sheets. Each prompt that
names a key gets a twin that names the pad's button, put where a sheet
is free; the patcher writes the texels and asm/padprompts.asm switches
the sprite to them while a pad is held. Each twin is one line of one
font, set and finished as the stock prompt it stands in for. With
GAMEDIR, an installed game, each model is also run on the stock
prompt's own words and compared with the stock texels, which is how the
numbers below were fitted.

  title    TITLE.TXR sheet 5, PRESS ENTER KEY: Times Bold, which Nimbus
           Roman Bold clones, a little wide and bolder across, filled
           with a gradient a row at a time over a black glow.
  attract  ADV_TXT.TXR sheet 0, PRESS ENTER KEY: a humanist bold italic
           set wide, which Open Sans Bold Italic comes closest to, white
           with a dark outline a texel wide.
  records  Record.txr sheet 13, PAGE UP KEY and PAGE DOWN KEY: a narrow
           bold grotesque, 9 px caps, as Liberation Sans Narrow Bold
           (Arial Narrow's metrics), white on clear.

The Device Settings page's two hint lines are made here as well, in the
face of the Options frame's own messages (OPTIONS.TXR sheet 4), which
is that narrow bold grotesque with 11 px caps. So are the masks for two
bitmaps the exe blits: the connection screen's SEARCH button (the lobby
patch) and SEL for TAB on the team room's button (the tabmenu patch),
in Noto Sans Mono, the closest open face to their monospaced 10 px
lettering.

Needs Pillow and the fonts; --check exits 77 with a note without them.
"""
import base64
import math
import os
import re
import struct
import subprocess
import sys
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TARGET = os.path.join(ROOT, 'sr2-patcher.py')

BEGIN = '# --- GENERATED by tools/prompts.py: BEGIN (do not edit) ---\n'
END = '# --- GENERATED by tools/prompts.py: END ---\n'
SKIPPED = 77

MISC = ('BINDATA', 'MISC')

# ---- the sheets ------------------------------------------------------


def sheet_count(game, name):
    folder = os.path.join(game, *MISC)
    found = {f.lower(): f for f in os.listdir(folder)}
    path = os.path.join(folder, found.get(name.lower() + '.bak', found.get(name.lower(), name)))
    with open(path, 'rb') as fh:
        return struct.unpack('<I', fh.read(8)[4:])[0]


def sheet(game, name, index):
    """(format, width, the texels) of one sheet of a .TXR under
    BINDATA\\MISC, from its .bak when the patcher has written the file,
    whatever the name's case on disc."""
    folder = os.path.join(game, *MISC)
    found = {f.lower(): f for f in os.listdir(folder)}
    path = os.path.join(folder, found.get(name.lower() + '.bak', found.get(name.lower(), name)))
    with open(path, 'rb') as fh:
        data = fh.read()
    if data[:4] != b'RTEX':
        raise SystemExit('%s is not a TXR' % path)
    off = 0x1000
    for i in range(index):
        off += struct.unpack_from('<4I', data, 16 + 16 * i)[2]
    fmt, width, nbytes, _ = struct.unpack_from('<4I', data, 16 + 16 * index)
    return fmt, width, list(struct.unpack_from('<%dH' % (nbytes // 2), data, off))


# ---- the title -------------------------------------------------------

TITLE_TXR, TITLE_SHEET = 'TITLE.TXR', 5
TITLE_KEYS, TITLE_PAD = 'PRESS ENTER KEY', 'PRESS START BUTTON'
TITLE_SIZE, TITLE_WIDE, TITLE_BOLD, TITLE_TRACK = 26.625, 1.025, 0.625, 0.8125
TITLE_X, TITLE_BASE = 49.875, 26          # the first letter's origin and the baseline, in the stock image
TITLE_ROWS = 34                           # the stock sprite's height
TITLE_CAPS = 8                            # the caps' first row
TITLE_GREEN = (15, 15, 15, 15, 15, 15, 15, 14, 14, 14, 13, 13, 13, 12, 12, 12, 12, 12)     # the fill a row at a time
TITLE_BLUE = (15, 15, 15, 14, 13, 12, 11, 10, 9, 7, 6, 4, 3, 2, 2, 1, 1, 1)                # down the caps, red 15 throughout
TITLE_SPREAD, TITLE_SIGMA, TITLE_GAIN = 8, 2.125, 1.175      # the glow: a disc of radius sqrt(8), blurred, gained
TITLE_STRIPS = ((3, 0), (42, 106))        # the stock image in the sheet: (first row, first column of the image) a strip
TITLE_AT = ((2, 77), (2, 110))            # where the pad's two halves go: rows 76 to 142 of the sheet are free
TITLE_BAND = (1, 33)                      # the image's rows that go there
SAMPLES = 8                               # the lettering is drawn this many times the size and averaged down


# The faces: what fontconfig calls each, the file names it may come back
# with, where the distributions put it, and the package to name when it
# is missing.
FACES = {
    'times': ('Nimbus Roman:style=Bold', ('NimbusRoman-Bold.otf', 'NimbusRoman-Bold.t1'),
              ('/usr/share/fonts/opentype/urw-base35/NimbusRoman-Bold.otf', '/usr/share/fonts/urw-base35/NimbusRoman-Bold.otf'),
              'Nimbus Roman Bold not found; install fonts-urw-base35 (Fedora: urw-base35-fonts)'),
    'narrow': ('Liberation Sans Narrow:style=Bold', ('LiberationSansNarrow-Bold.ttf',),
               ('/usr/share/fonts/truetype/liberation-sans-narrow/LiberationSansNarrow-Bold.ttf', '/usr/share/fonts/liberation-narrow/LiberationSansNarrow-Bold.ttf'),
               'Liberation Sans Narrow Bold not found; install fonts-liberation-sans-narrow (Fedora: liberation-narrow-fonts)'),
    'italic': ('Open Sans:style=Bold Italic', ('OpenSans-BoldItalic.ttf',),
               ('/usr/share/fonts/truetype/open-sans/OpenSans-BoldItalic.ttf', '/usr/share/fonts/open-sans/OpenSans-BoldItalic.ttf'),
               'Open Sans Bold Italic not found; install fonts-open-sans (Fedora: open-sans-fonts)'),
    'japanese': ('Noto Sans CJK JP:style=Bold', ('NotoSansCJK-VF.ttc', 'NotoSansCJK-Bold.ttc', 'NotoSansCJKjp-Bold.otf', 'NotoSansJP-Bold.otf', 'NotoSansJP[wght].ttf'),
                 ('/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc', '/usr/share/fonts/google-noto-sans-cjk-vf-fonts/NotoSansCJK-VF.ttc'),
                 'Noto Sans CJK JP Bold not found; install fonts-noto-cjk (Fedora: google-noto-sans-cjk-vf-fonts)'),
}
JAPANESE_WEIGHT = 700
_fonts = {}


def face(name, size):
    """A face at a size, from one of its known paths, else wherever
    fontconfig says it is."""
    from PIL import ImageFont
    if (name, size) not in _fonts:
        match, files, paths, missing = FACES[name]
        paths = list(paths)
        try:
            found = subprocess.run(['fc-match', '-f', '%{file}', match], capture_output=True, text=True, timeout=10).stdout.strip()
            if os.path.basename(found) in files:
                paths.append(found)
        except (OSError, subprocess.SubprocessError):
            pass
        path = next((p for p in paths if os.path.isfile(p)), None)
        if path is None:
            raise SystemExit(missing)
        fnt = ImageFont.truetype(path, size)
        if name == 'japanese':
            try:
                axes = fnt.get_variation_axes()
                fnt.set_variation_by_axes([JAPANESE_WEIGHT if a['name'] in (b'Weight', 'Weight') else a['default'] for a in axes])
            except OSError:
                pass                    # a static Bold file
        _fonts[name, size] = fnt
    return _fonts[name, size]


def lettering(name, text, width, height, x, base, size, wide=1.0, bold=0.0, track=0.0, space=0.0):
    """A line's coverage, 0..1, a row a list: the face at a size in
    pixels, its first letter's origin at x and its baseline at base, set
    wide times as wide, bold pixels bolder across, the letters track
    pixels apart and the spaces space wider. Drawn SAMPLES times the size
    and averaged down."""
    return averaged(drawn(name, text, width, height, x, base, size, wide, bold, track, space), width, height)


def averaged(big, width, height):
    """A drawn line's coverage, 0..1, a row a list."""
    from PIL import Image
    flat = big.crop((0, 0, width * SAMPLES, height * SAMPLES)).resize((width, height), Image.BOX).tobytes()
    return [[flat[y * width + col] / 255.0 for col in range(width)] for y in range(height)]


def drawn(name, text, width, height, x, base, size, wide=1.0, bold=0.0, track=0.0, space=0.0):
    """A line as lettering() draws it, SAMPLES times the size, an L image."""
    from PIL import Image, ImageChops, ImageDraw
    fnt = face(name, size * SAMPLES)
    big_w = int(width * SAMPLES / wide) + 4 * SAMPLES
    big = Image.new('L', (big_w, height * SAMPLES), 0)
    draw = ImageDraw.Draw(big)
    at = x * SAMPLES / wide
    for ch in text:
        draw.text((at, base * SAMPLES), ch, font=fnt, fill=255, anchor='ls')
        at += fnt.getlength(ch) + (track + (space if ch == ' ' else 0)) * SAMPLES / wide
    spread_by = int(round(bold * SAMPLES / wide))
    out = big.copy()
    if spread_by:
        for dx in range(-(spread_by // 2), spread_by - spread_by // 2 + 1):
            moved = Image.new('L', big.size, 0)
            moved.paste(big, (-dx, 0))
            out = ImageChops.lighter(out, moved)
    if wide != 1.0:
        out = out.resize((int(round(big_w * wide)), height * SAMPLES), Image.LANCZOS)
    return out


def title_coverage(text, width):
    return lettering('times', text, width, TITLE_ROWS, TITLE_X, TITLE_BASE, TITLE_SIZE, TITLE_WIDE, TITLE_BOLD, TITLE_TRACK)


def spread(cov, r2):
    """Each texel the most of those within sqrt(r2) of it."""
    h, w = len(cov), len(cov[0])
    reach = int(math.sqrt(r2))
    offsets = [(dy, dx) for dy in range(-reach, reach + 1) for dx in range(-reach, reach + 1) if dy * dy + dx * dx <= r2]
    out = [[0.0] * w for _ in range(h)]
    for y in range(h):
        for dy, dx in offsets:
            if not 0 <= y + dy < h:
                continue
            src, dst = cov[y + dy], out[y]
            for x in range(max(0, -dx), min(w, w - dx)):
                if src[x + dx] > dst[x]:
                    dst[x] = src[x + dx]
    return out


def blurred(a, sigma):
    """A Gaussian blur, nothing beyond the edges."""
    h, w = len(a), len(a[0])
    reach = int(math.ceil(sigma * 4))
    kernel = [math.exp(-0.5 * (i / sigma) ** 2) for i in range(-reach, reach + 1)]
    total = sum(kernel)
    kernel = [k / total for k in kernel]
    cols = [[sum(kernel[i + reach] * a[y + i][x] for i in range(-reach, reach + 1) if 0 <= y + i < h) for x in range(w)] for y in range(h)]
    return [[sum(kernel[i + reach] * row[x + i] for i in range(-reach, reach + 1) if 0 <= x + i < w) for x in range(w)] for row in cols]


def title_image(text, width):
    """The prompt as 4444 texels, a row a list: the gradient through the
    lettering, over the glow."""
    cov = title_coverage(text, width)
    glow = blurred(spread(cov, TITLE_SPREAD), TITLE_SIGMA)
    out = []
    for y in range(TITLE_ROWS):
        i = min(max(y - TITLE_CAPS, 0), len(TITLE_GREEN) - 1)
        fill = (15, TITLE_GREEN[i], TITLE_BLUE[i])
        row = []
        for x in range(width):
            c = cov[y][x]
            alpha = c + (1 - c) * min(1.0, glow[y][x] * TITLE_GAIN)
            a = int(round(alpha * 15))
            if not a:
                row.append(0)
                continue
            r, g, b = (int(round(min(15.0, c * v / alpha))) for v in fill)
            row.append(a << 12 | r << 8 | g << 4 | b)
        out.append(row)
    return out, cov


def title_stock(texels):
    """The stock prompt, whole, from its two strips in the sheet."""
    (row0, col0), (row1, col1) = TITLE_STRIPS
    out = []
    for r in range(TITLE_ROWS):
        a, b = texels[(row0 + r) * 256:(row0 + r + 1) * 256], texels[(row1 + r) * 256:(row1 + r + 1) * 256]
        if a[col1:] != b[:256 - col1]:
            raise SystemExit('TITLE.TXR: the prompt\'s two strips do not overlap as expected')
        out.append(a + b[256 - col1:])
    return out


def levels(a, b):
    """How far apart two 4444 texels are, the most over their channels."""
    return max(abs((a >> s & 15) - (b >> s & 15)) for s in (12, 8, 4, 0))


def title(game, log):
    if game:
        fmt, width, texels = sheet(game, TITLE_TXR, TITLE_SHEET)
        if (fmt, width, len(texels)) != (8, 256, 256 * 256):
            raise SystemExit('TITLE.TXR sheet %d is not a 256x256 4444' % TITLE_SHEET)
        stock = title_stock(texels)
        keys, _cov = title_image(TITLE_KEYS, len(stock[0]))
        apart = [levels(s, k) for srow, krow in zip(stock, keys) for s, k in zip(srow, krow) if s >> 12 or k >> 12]
        log('title: the model of %s against the stock: %d of %d texels differ, %d by more than one level of 15, %d by more than two'
            % (TITLE_KEYS, sum(d > 0 for d in apart), len(apart), sum(d > 1 for d in apart), sum(d > 2 for d in apart)))
    wide = 480
    pad, cov = title_image(TITLE_PAD, wide)
    ink = [x for x in range(wide) if any(cov[y][x] >= 0.02 for y in range(TITLE_ROWS))]
    lit = [x for x in range(wide) if any(pad[y][x] >> 12 for y in range(TITLE_ROWS))]
    margin = max(ink[0] - lit[0], lit[-1] - ink[-1]) + 2
    left, right = ink[0] - margin, ink[-1] + 1 + margin
    right += (right - left) & 1
    rows = [y for y in range(TITLE_ROWS) if any(t >> 12 for t in pad[y])]
    if rows[0] < TITLE_BAND[0] or rows[-1] >= TITLE_BAND[1]:
        raise SystemExit('the title\'s glow reaches rows %d to %d, past the band' % (rows[0], rows[-1]))
    half = (right - left) // 2
    if half > 250:
        raise SystemExit('the title is %d texels wide, too wide for two strips' % (right - left))
    log('title: %s, %d wide in two strips of %d' % (TITLE_PAD, right - left, half))
    blits = []
    for (x, y), first in zip(TITLE_AT, (left, left + half)):
        strip = [t for row in pad[TITLE_BAND[0]:TITLE_BAND[1]] for t in row[first:first + half]]
        blits.append((TITLE_TXR, TITLE_SHEET, x, y, half, TITLE_BAND[1] - TITLE_BAND[0], '', strip))
    return blits


def share(model, stock):
    """How far a model's coverage is from the stock's: the squared
    difference as a share of the stock's ink."""
    return sum((m - s) ** 2 for mrow, srow in zip(model, stock) for m, s in zip(mrow, srow)) / sum(s for row in stock for s in row)


# ---- the attract screen ----------------------------------------------

ATTRACT_TXR, ATTRACT_SHEET = 'ADV_TXT.TXR', 0
ATTRACT_KEYS, ATTRACT_PAD = 'PRESS ENTER KEY', 'PRESS START BUTTON'
ATTRACT_SIZE, ATTRACT_WIDE, ATTRACT_TRACK, ATTRACT_SPACE = 21.0, 1.25, -1.5, 0.25
ATTRACT_X, ATTRACT_BASE = 29.9375, 17.125      # the first letter's origin and the baseline, in the stock image
ATTRACT_ROWS = 19                         # the stock image: rows 217 to 235 of its sheet, every column
ATTRACT_TOP = 217
ATTRACT_INK = 10                          # of 31: fainter coverage than this is outline, not lettering
ATTRACT_OUTLINE = 0x8842                  # the outline's texel, 1555: every texel beside the lettering, corners too
ATTRACT_ON = 3                            # the sheet the pad's prompt goes on: rows 172 to 255 are free
ATTRACT_AT = (2, 176)


def attract_image(text, width):
    """The prompt as 1555 texels, a row a list, and its coverage: white
    lettering, greys at its edges, the outline round it."""
    cov = lettering('italic', text, width, ATTRACT_ROWS, ATTRACT_X, ATTRACT_BASE, ATTRACT_SIZE, ATTRACT_WIDE, 0.0, ATTRACT_TRACK, ATTRACT_SPACE)
    grey = [[int(round(c * 31)) for c in row] for row in cov]
    out = []
    for y in range(ATTRACT_ROWS):
        row = []
        for x in range(width):
            g = grey[y][x]
            if g >= ATTRACT_INK:
                row.append(0x8000 | g << 10 | g << 5 | g)
            elif any(grey[yy][xx] >= ATTRACT_INK for yy in range(max(0, y - 1), min(ATTRACT_ROWS, y + 2)) for xx in range(max(0, x - 1), min(width, x + 2))):
                row.append(ATTRACT_OUTLINE)
            else:
                row.append(0)
        out.append(row)
    return out, cov


def attract(game, log):
    if game:
        fmt, width, texels = sheet(game, ATTRACT_TXR, ATTRACT_SHEET)
        if (fmt, width, len(texels)) != (2, 256, 256 * 256):
            raise SystemExit('ADV_TXT.TXR sheet %d is not a 256x256 1555' % ATTRACT_SHEET)
        stock = [texels[(ATTRACT_TOP + y) * 256:(ATTRACT_TOP + y + 1) * 256] for y in range(ATTRACT_ROWS)]
        keys, cov = attract_image(ATTRACT_KEYS, 256)
        white = [[(t >> 10 & 31) / 31.0 if t >> 15 and t != ATTRACT_OUTLINE else 0.0 for t in row] for row in stock]
        inked = [[c if c * 31 >= ATTRACT_INK - 0.5 else 0.0 for c in row] for row in cov]
        log('attract: the model of %s against the stock: %.1f%% of the ink off, %d of %d texels differ in being clear, outline or lettering'
            % (ATTRACT_KEYS, 100 * share(inked, white), sum((s == 0, s == ATTRACT_OUTLINE) != (k == 0, k == ATTRACT_OUTLINE) for srow, krow in zip(stock, keys) for s, k in zip(srow, krow)),
               sum(bool(s) or bool(k) for srow, krow in zip(stock, keys) for s, k in zip(srow, krow))))
    wide = 320
    pad, _cov = attract_image(ATTRACT_PAD, wide)
    lit = [x for x in range(wide) if any(pad[y][x] for y in range(ATTRACT_ROWS))]
    width = lit[-1] - lit[0] + 1
    if ATTRACT_AT[0] + width + 1 > 256:
        raise SystemExit('the attract prompt is %d texels wide, too wide for its sheet' % width)
    if any(pad[0]) or not any(pad[1]):
        raise SystemExit('the attract prompt\'s outline does not start on the second row')
    log('attract: %s, %d by %d' % (ATTRACT_PAD, width, ATTRACT_ROWS))
    return [(ATTRACT_TXR, ATTRACT_ON, ATTRACT_AT[0], ATTRACT_AT[1], width, ATTRACT_ROWS, '', [t for row in pad for t in row[lit[0]:lit[0] + width]])]


# ---- the Records pages -----------------------------------------------

RECORD_TXR, RECORD_SHEET = 'Record.txr', 13
RECORD_PAD = (('LB BUTTON', 64), ('RB BUTTON', 84))     # the lines and their baselines, as rows of the sheet: the stock's 34 rows down, where it has a second arrow
RECORD_CAPS = 9                           # the caps' height, whole, so their tops and feet are sharp as the stock's are
RECORD_CAP_RATIO = 1409 / 2048.0          # the face's cap height to its size
RECORD_WIDE, RECORD_BOLD, RECORD_TRACK, RECORD_SPACE = 0.9, 0.125, 0.0, 0.15625
RECORD_X = 33.5                           # the first letter's origin, a column of the sheet: its stem a full texel then half, on the stock P's
RECORD_AT = (31, 53, 81, 33)              # the L LEVER and R LEVER lettering, which no entry draws: x, y, width, height
RECORD_WHITE = 0x0fff                     # the sheet's lettering is white, its alpha the shape


def record_line(text, base, x0, y0, width, height):
    """A line's coverage over a rectangle of the sheet."""
    return lettering('narrow', text, width, height, RECORD_X - x0, base - y0, RECORD_CAPS / RECORD_CAP_RATIO, RECORD_WIDE, RECORD_BOLD, RECORD_TRACK, RECORD_SPACE)


def record(_game, log):
    x0, y0, w, h = RECORD_AT
    area = [[0.0] * w for _ in range(h)]
    for text, base in RECORD_PAD:
        for y, row in enumerate(record_line(text, base, x0, y0, w, h)):
            for x, c in enumerate(row):
                area[y][x] = max(area[y][x], c)
    if any(area[0]) or any(area[-1]) or any(row[0] or row[-1] for row in area):
        raise SystemExit('the Records lettering reaches the edge of its rectangle')
    log('records: %s and %s at (%d, %d), %d by %d' % (RECORD_PAD[0][0], RECORD_PAD[1][0], x0, y0, w, h))
    return [(RECORD_TXR, RECORD_SHEET, x0, y0, w, h, '', [int(round(c * 15)) << 12 | RECORD_WHITE for row in area for c in row])]


# ---- the Device Settings page's hint bar ------------------------------

# The page's two lines, in the face the frame's own messages are in
# (OPTIONS.TXR sheet 4, a narrow bold grotesque with 11 px caps), dark
# on white. Each is cut in two at the word gap nearest its middle,
# because a line is wider than the sheet, and each half is a strip with
# a margin of white each side, so its edges filter to white. They go on
# the sheet the patcher appends to OPTIONS.TXR.
HINT_TXR, HINT_STOCK = 'OPTIONS.TXR', 4
HINT_KEYS = ('Hit the ESC key to go back to the', 58, 46)     # a stock line's first words, the row its strip starts on and a column left of it
HINT_LINES = ('Select an action and hit the key to bind it', 'Hit the button to bind it, or hit ESC to keep it')
HINT_SHEET = 12                           # the appended sheet
HINT_TOPS = (130, 150, 170, 190)          # the strips' rows on it, from column 1
HINT_ROWS, HINT_MARGIN = 17, 2            # a strip starts a row above the ascenders, as the stock's do
HINT_CAPS = 11
HINT_WIDE, HINT_BOLD, HINT_TRACK = 0.9, 0.5, 0.75
HINT_X, HINT_BASE = 3.3125, 12.625        # the first letter's origin past the column, and the baseline, in a strip
HINT_GAP = 3                              # clear columns that make a word gap


def hint_line(text, width):
    return lettering('narrow', text, width, HINT_ROWS, HINT_X, HINT_BASE, HINT_CAPS / RECORD_CAP_RATIO, HINT_WIDE, HINT_BOLD, HINT_TRACK)


def halves(cov):
    """A line's coverage cut in two at the word gap nearest its middle:
    (first column, cut column, column after the last) of the ink."""
    rows, width = len(cov), len(cov[0])
    inked = [any(int(round(cov[y][x] * 15)) for y in range(rows)) for x in range(width)]
    first, last = inked.index(True), width - 1 - inked[::-1].index(True)
    gaps, x = [], first
    while x <= last:                        # the word gaps: runs of clear columns
        if not inked[x]:
            end = x
            while not inked[end]:
                end += 1
            if end - x >= HINT_GAP:
                gaps.append((x + end) // 2)
            x = end
        x += 1
    if not gaps:
        raise SystemExit('no word gap to cut a line at')
    return first, min(gaps, key=lambda g: abs(g - (first + last) / 2.0)), last + 1


def strip(cov, a, b, ink=0xf000, paper=0xffff):
    """A strip of 4444 texels from columns a to b of a line's coverage,
    with HINT_MARGIN texels of paper each side: the ink's colour by the
    coverage, over the paper's."""
    out = []
    for row in cov:
        values = [0.0] * HINT_MARGIN + row[a:b] + [0.0] * HINT_MARGIN
        for c in values:
            level = int(round(c * 15))
            out.append(paper if not level else (ink if level == 15 else
                       0xf000 | sum(int(round((paper >> s & 15) * (15 - level) / 15.0 + (ink >> s & 15) * level / 15.0)) << s for s in (8, 4, 0))))
    return out


def line_strips(cov, file, sheet_, tops, variant='', ink=0xf000, paper=0xffff):
    """A line's two halves as blits at the given rows of a sheet."""
    first, cut, end = halves(cov)
    blits = []
    for (a, b), top in zip(((first, cut), (cut, end)), tops):
        w = b - a + 2 * HINT_MARGIN
        if 1 + w > 255:
            raise SystemExit('half of a line is %d texels wide, too wide for the sheet' % w)
        blits.append((file, sheet_, 1, top, w, len(cov), variant, strip(cov, a, b, ink, paper)))
    return blits


def hints(game, log):
    if game:
        fmt, width, texels = sheet(game, HINT_TXR, HINT_STOCK)
        if (fmt, width, len(texels)) != (0, 256, 256 * 256):
            raise SystemExit('OPTIONS.TXR sheet %d is not a 256x256 565' % HINT_STOCK)
        text, top, left = HINT_KEYS
        dark = lambda t: 1 - ((t >> 11) * 2 + (t >> 5 & 63) + (t & 31) * 2) / 187.0
        stock = [[d if d >= 0.06 else 0.0 for d in (dark(texels[(top + y) * 256 + x]) for x in range(left, 256))] for y in range(HINT_ROWS)]
        log('hints: the model of "%s" against the stock: %.1f%% of the ink off' % (text, 100 * share(hint_line(text, 256 - left), stock)))
    blits = []
    for text, tops in zip(HINT_LINES, (HINT_TOPS[:2], HINT_TOPS[2:])):
        cov = hint_line(text, 520)
        if any(int(round(c * 15)) for c in cov[0] + cov[-1]):
            raise SystemExit('the hint lettering reaches the edge of its strip')
        blits += line_strips(cov, HINT_TXR, HINT_SHEET, tops)
        first, cut, end = halves(cov)
        log('hints: "%s", %d wide, cut at %d' % (text, end - first, cut - first))
    return blits


# ---- the hint bars, the gallery and the replay prompt -----------------

# The stock screens' bars that name a key, and what the pad's say. The
# Records page and the Options frame both show the first; the Replay
# Gallery shows the second at its foot and the second and third on its
# popups. The Japanese files (Sega's Japanese and the DigiCube and
# MediaKite releases) have Record.txr's and the RG files' lines in
# Japanese, with their own wording on the popups; the Options frame's
# line is English in every release.
BAR_PAD = 'Use the D-pad to change mode selections'               # for: Use Cursor keys to change mode selections
BACK_PAD = 'Hit the B button to go back to the previous screen'    # for: Hit the ESC key to go back to the previous screen
BACK2_PAD = 'Go back to the previous screen by pressing the B button'    # for: Go back to the previous screen by pressing the ESC key
# The Records bar's bubble is a separate sprite the stock line's width
# (406 texels of lettering); the pad's line must stay within it.
BAR_PAD_JP = '十字ボタンで項目を選択してください。Bボタンで戻ります。'          # for: ↑↓←→で項目を選択してください。ESCキーで前画面に戻ります。 (397 wide; with 前画面に, 456)
BACK_PAD_JP = 'Bボタンで前画面に戻ります。'                               # for: ESCキーで前画面に戻ります。
BACK2_PAD_JP = '↑↓で選択、Aボタンで決定。Bボタンで前画面に戻ります。'          # for: ↑↓で選択、ENTERキーで決定。ESCキーで前画面に戻ります。, the popups' first line
BACK3_PAD_JP = '←→で選択、Aボタンで決定。Bボタンで前画面に戻ります。'          # for: ←→で選択、ENTERキーで決定。ESCキーで前画面に戻ります。, their second
JP_SIZE, JP_WIDE, JP_X, JP_BASE = 14.0, 1.05, 3.5, 14.0            # Noto Sans CJK JP Bold against a stock Japanese line
BAR_WIDEST = 410                          # the bubbles behind the bars are sprites of their own, the stock lines' width: 406 the Records bar's, 381 and 386 the popups'
# The Device Settings page's lines with a pad; HINT_LINES are the keyboard's.
DEVICES_PAD = ('Select an action and hit the button to bind it', 'Hit the button to bind it, or hold START to keep it')
RECORD_STRIPS = 15                        # the sheet the patcher appends to Record.txr: tops 2, 22 the English line's halves, 42, 62 the Japanese
GALLERY_TXRS = ('RG_10.txr', 'RG_AC.txr', 'RG_RG.txr', 'RG_TA.txr')
GALLERY_STRIPS = 9                        # the sheet appended to each RG file
GALLERY_TOPS = {'back': (2, 20), 'back_jp': (38, 56), 'back2': (74, 92), 'back2_jp': (110, 128), 'back3': (146, 164), 'back3_jp': (182, 200)}
OPTIONS_STRIPS = 13                       # the sheet appended to OPTIONS.TXR after the devices patch's twelfth
OPTIONS_TOPS = {'bar': (2, 22), 'devices1': (42, 62), 'devices2': (82, 102)}


def jp_line(text, width):
    return lettering('japanese', text, width, HINT_ROWS, JP_X, JP_BASE, JP_SIZE, JP_WIDE)


def bars(game, log):
    """The pad's bar lines: Record.txr's and the RG files' appended
    sheets, English and Japanese, and OPTIONS.TXR's with the Device
    Settings page's two."""
    lines = {'bar': hint_line(BAR_PAD, 520), 'back': hint_line(BACK_PAD, 560), 'back2': hint_line(BACK2_PAD, 600),
             'bar_jp': jp_line(BAR_PAD_JP, 520), 'back_jp': jp_line(BACK_PAD_JP, 300), 'back2_jp': jp_line(BACK2_PAD_JP, 520), 'back3_jp': jp_line(BACK3_PAD_JP, 520),
             'devices1': hint_line(DEVICES_PAD[0], 560), 'devices2': hint_line(DEVICES_PAD[1], 560)}
    for name, text in (('bar', BAR_PAD), ('back', BACK_PAD), ('back2', BACK2_PAD), ('bar_jp', BAR_PAD_JP), ('back_jp', BACK_PAD_JP), ('back2_jp', BACK2_PAD_JP), ('back3_jp', BACK3_PAD_JP), ('devices1', DEVICES_PAD[0]), ('devices2', DEVICES_PAD[1])):
        cov = lines[name]
        if any(int(round(c * 15)) for c in cov[0] + cov[-1]):
            raise SystemExit('"%s" reaches the edge of its strip' % text)
        first, cut, end = halves(cov)
        log('bars: "%s", %d wide, cut at %d' % (text, end - first, cut - first))
        if end - first > BAR_WIDEST:
            raise SystemExit('"%s" is %d wide; the bars\' bubbles take %d' % (text, end - first, BAR_WIDEST))
    blits = line_strips(lines['bar'], RECORD_TXR, RECORD_STRIPS, (2, 22), 'en') + line_strips(lines['bar_jp'], RECORD_TXR, RECORD_STRIPS, (42, 62), 'jp')
    for file in GALLERY_TXRS:
        blits += line_strips(lines['back'], file, GALLERY_STRIPS, GALLERY_TOPS['back'], 'en')
        blits += line_strips(lines['back_jp'], file, GALLERY_STRIPS, GALLERY_TOPS['back_jp'], 'jp')
        blits += line_strips(lines['back'], file, GALLERY_STRIPS, GALLERY_TOPS['back2'], 'en')
        blits += line_strips(lines['back2_jp'], file, GALLERY_STRIPS, GALLERY_TOPS['back2_jp'], 'jp')
        blits += line_strips(lines['back2'], file, GALLERY_STRIPS, GALLERY_TOPS['back3'], 'en')
        blits += line_strips(lines['back3_jp'], file, GALLERY_STRIPS, GALLERY_TOPS['back3_jp'], 'jp')
    blits += line_strips(lines['bar'], HINT_TXR, OPTIONS_STRIPS, OPTIONS_TOPS['bar'])
    blits += line_strips(lines['devices1'], HINT_TXR, OPTIONS_STRIPS, OPTIONS_TOPS['devices1'])
    blits += line_strips(lines['devices2'], HINT_TXR, OPTIONS_STRIPS, OPTIONS_TOPS['devices2'])
    return blits


# The gallery's sort box: the SORT header, white on clear, and three
# plates, black on white, 71 by 13 each, in the face of the lobby's
# labels (URW Gothic Demi, ITC Avant Garde Gothic's clone) fitted to
# the stock plates. With a pad, LB and RB step the sort, so the plates
# name no key and the header names the two.
FACES['gothic'] = ('URW Gothic:style=Demi', ('URWGothic-Demi.otf', 'URWGothic-Demi.t1'),
                   ('/usr/share/fonts/opentype/urw-base35/URWGothic-Demi.otf', '/usr/share/fonts/urw-base35/URWGothic-Demi.otf'),
                   'URW Gothic Demi not found; install fonts-urw-base35 (Fedora: urw-base35-fonts)')
PLATE_SIZE, PLATE_WIDE, PLATE_BASE = 12.25, 1.0, 11.0
PLATE_W, PLATE_H = 71, 13
PLATES = (('SORT LB/RB', 'header'), ('MODE', 'plate'), ('CAR', 'plate'), ('DATE', 'plate'))
PLATE_AT = {'MODE': (2, 220), 'CAR': (76, 220), 'DATE': (150, 220), 'SORT LB/RB': (2, 236)}


def plate(text, kind):
    """A plate's texels: the text centred, white on clear for the header,
    black on white for a plate."""
    cov = lettering('gothic', text, PLATE_W + 60, PLATE_H, 4.0, PLATE_BASE, PLATE_SIZE, PLATE_WIDE)
    cols = [x for x in range(PLATE_W + 60) if any(int(round(cov[y][x] * 15)) for y in range(PLATE_H))]
    width = cols[-1] - cols[0] + 1
    if width > PLATE_W - 4:
        raise SystemExit('%s is %d texels wide, too wide for a plate' % (text, width))
    left = (PLATE_W - width) // 2
    out = []
    for row in cov:
        line = [0.0] * left + row[cols[0]:cols[-1] + 1] + [0.0] * (PLATE_W - left - width)
        for c in line:
            level = int(round(c * 15))
            if kind == 'header':
                out.append(level << 12 | 0xfff)
            else:
                g = 15 - level
                out.append(0xf000 | g << 8 | g << 4 | g)
    return out


def gallery(game, log):
    if game:
        fmt, width, texels = sheet(game, GALLERY_TXRS[0], 7)
        if (fmt, width) != (8, 128):
            raise SystemExit('RG_10.txr sheet 7 is not a 128x128 4444')
        stock = [[1 - (texels[y * 128 + x] & 15) / 15.0 if texels[y * 128 + x] >> 12 else 0.0 for x in range(2, 73)] for y in range(22, 35)]
        model = lettering('gothic', 'MODE : F6', PLATE_W, PLATE_H, 8.0, PLATE_BASE, PLATE_SIZE, PLATE_WIDE)
        log('gallery: the model of MODE : F6 against the stock plate: %.1f%% of the ink off' % (100 * share(model, stock)))
    blits = []
    for file in GALLERY_TXRS:
        for text, kind in PLATES:
            x, y = PLATE_AT[text]
            blits.append((file, GALLERY_STRIPS, x, y, PLATE_W, PLATE_H, '', plate(text, kind)))
    log('gallery: %s' % ', '.join(text for text, _kind in PLATES))
    return blits


# The ranking's PRESS ENTER KEY for REPLAY: on sheet 9 of the three Rank
# files and Record.txr, a 166 by 24 plate (rows 190 to 213) with PRESS and
# for REPLAY in white and ENTER KEY larger in yellow, every letter
# outlined in black. The pad's, PRESS A BUTTON for REPLAY, goes on rows
# 213 to 236, over Dreamcast memory-card text no entry draws.
FACES['sans'] = ('Nimbus Sans:style=Bold Italic', ('NimbusSans-BoldItalic.otf', 'NimbusSans-BoldItalic.t1'),
                 ('/usr/share/fonts/opentype/urw-base35/NimbusSans-BoldItalic.otf', '/usr/share/fonts/urw-base35/NimbusSans-BoldItalic.otf'),
                 'Nimbus Sans Bold Italic not found; install fonts-urw-base35 (Fedora: urw-base35-fonts)')
REPLAY_TXRS = ('Rank10.txr', 'RankAC.txr', 'RankTA.txr', 'Record.txr')
REPLAY_SHEET, REPLAY_AT, REPLAY_W, REPLAY_H = 9, (2, 213), 166, 24
REPLAY_PLATE, REPLAY_WHITE, REPLAY_YELLOW, REPLAY_INK = 0xf887, 0xffff, 0xffb0, 0xf000
REPLAY_BASE = 16                          # the baseline's row in the plate
REPLAY_SMALL, REPLAY_LARGE = (11.0, 0.85, 1.0), (14.0, 0.85, 1.0)   # the white and the yellow words' size, width and boldness, for the stock's 8 and 10 px caps
REPLAY_GAPS = (1, 1)                      # before and after the yellow words, outlines included
REPLAY_OUTLINE = 1.125                   # the black outline's reach around a letter, texels
REPLAY_OUTLINE_GAIN = 2.0                # the outline's coverage times this, capped at 1: harder edges
REPLAY_WORDS = (('PRESS', REPLAY_SMALL, REPLAY_WHITE), ('A BUTTON', REPLAY_LARGE, REPLAY_YELLOW), ('for REPLAY', REPLAY_SMALL, REPLAY_WHITE))


def replay(_game, log):
    from PIL import ImageFilter
    parts = []
    reach = 2 * int(round(REPLAY_OUTLINE * SAMPLES)) + 1
    for text, (size, wide, bold), colour in REPLAY_WORDS:
        big = drawn('sans', text, 200, REPLAY_H, 8.0, REPLAY_BASE, size, wide, bold)
        cov = averaged(big, 200, REPLAY_H)
        edge = averaged(big.filter(ImageFilter.MaxFilter(reach)), 200, REPLAY_H)     # the letters and their outline
        cols = [x for x in range(200) if any(c >= 0.1 for c in (edge[y][x] for y in range(REPLAY_H)))]     # the outline included
        parts.append((colour, [row[cols[0]:cols[-1] + 1] for row in cov], [row[cols[0]:cols[-1] + 1] for row in edge]))
    width = sum(len(part[1][0]) for part in parts) + sum(REPLAY_GAPS)
    if width > REPLAY_W - 2:
        raise SystemExit('the replay prompt is %d texels wide, too wide for its plate' % width)
    ink = [[(0, 0.0, 0.0)] * REPLAY_W for _ in range(REPLAY_H)]    # (colour, the letter's coverage, the outline's) a texel
    x = (REPLAY_W - width) // 2
    for i, (colour, cov, edge) in enumerate(parts):
        for y in range(REPLAY_H):
            for dx in range(len(cov[y])):
                old = ink[y][x + dx]
                if cov[y][dx] > old[1]:
                    ink[y][x + dx] = (colour, cov[y][dx], max(edge[y][dx], old[2]))
                else:
                    ink[y][x + dx] = (old[0], old[1], max(edge[y][dx], old[2]))
        x += len(cov[0]) + (REPLAY_GAPS[i] if i < 2 else 0)
    out = []
    for y in range(REPLAY_H):
        for x in range(REPLAY_W):
            colour, c, o = ink[y][x]
            o = min(1.0, o * REPLAY_OUTLINE_GAIN)
            texel = 0xf000
            for shift in (8, 4, 0):
                plate, letter = REPLAY_PLATE >> shift & 15, colour >> shift & 15
                texel |= int(round(plate * (1 - o) + letter * c)) << shift     # black where the outline is and the letter is not
            out.append(texel)
    log('replay: %s, %d wide on the %d plate' % (' '.join(w for w, _s, _c in REPLAY_WORDS), width, REPLAY_W))
    return [(file, REPLAY_SHEET, REPLAY_AT[0], REPLAY_AT[1], REPLAY_W, REPLAY_H, '', out) for file in REPLAY_TXRS]


def records(game, log):
    return record(game, log) + replay(game, log) + [b for b in bars(game, log) if b[0] == RECORD_TXR]


def gallery_all(game, log):
    return [b for b in bars(game, lambda _l: None) if b[0] in GALLERY_TXRS] + gallery(game, log)


def options_all(game, log):
    return [b for b in bars(game, lambda _l: None) if b[0] == HINT_TXR]


# The connection screen's SEARCH button (BINDATA\connect\button\showteam_*.BMP,
# relettered by the lobby patch) and the team room's TAB button
# (BINDATA\chat\tab_menu_on.BMP and _on2.BMP, SEL on the pad's copies the
# tabmenu patch writes): 24-bit bitmaps the exe blits, their lettering a
# monospaced sans with 10 px caps. The art is a mask: 4444 texels whose
# alpha is the coverage, which the patcher lays over the stock face in
# the stock lettering's colour.
FACES['mono'] = ('Noto Sans Mono:style=Regular', ('NotoSansMono-Regular.ttf',),
                 ('/usr/share/fonts/truetype/noto/NotoSansMono-Regular.ttf', '/usr/share/fonts/google-noto/NotoSansMono-Regular.ttf'),
                 'Noto Sans Mono Regular not found; install fonts-noto-mono (Fedora: google-noto-sans-mono-fonts)')
MONO_SIZE, MONO_WIDE, MONO_TRACK = 13.5, 0.925, 1.0
BUTTON_FILE, BUTTON_W, BUTTON_H, BUTTON_BASE = 'showteam', 102, 16, 12.5      # the lobby button's face; the stock caps are rows 3 to 12
BUTTON_TEXT, BUTTON_STOCK = 'SEARCH', 'SHOW TEAMS'
TAB_FILE, TAB_BOX, TAB_BASE = 'tab_menu', (9, 3, 26, 12), 10.5                 # TAB's letters, rows 4 to 13 and columns 10 to 33 of the file, with a pixel round them
TAB_TEXT = 'SEL'


def mask(text, width, height, centre, base):
    """A line's coverage as 4444 texels, alpha the level, centred on a
    column."""
    cov = lettering('mono', text, width + 40, height, 10.0, base, MONO_SIZE, MONO_WIDE, 0.0, MONO_TRACK)
    cols = [x for x in range(width + 40) if any(int(round(cov[y][x] * 15)) for y in range(height))]
    shift = int(round(centre - (cols[0] + cols[-1]) / 2.0))
    if cols[0] + shift < 0 or cols[-1] + shift >= width:
        raise SystemExit('%s is %d texels wide, too wide for its %d' % (text, cols[-1] - cols[0] + 1, width))
    return [int(round(cov[y][x - shift] * 15)) << 12 if 0 <= x - shift < width + 40 else 0 for y in range(height) for x in range(width)]


def buttons(game, log):
    if game:
        from PIL import Image
        path = os.path.join(game, 'BINDATA', 'connect', 'button', 'showteam_on.BMP')
        if os.path.isfile(path + '.bak'):
            path += '.bak'
        if os.path.isfile(path):
            im = Image.open(path).convert('L')
            stock = [[max(0.0, 1 - im.getpixel((x, y)) / 255.0) for x in range(BUTTON_W)] for y in range(BUTTON_H)]
            model = lettering('mono', BUTTON_STOCK, BUTTON_W, BUTTON_H, 9.0, BUTTON_BASE, MONO_SIZE, MONO_WIDE, 0.0, MONO_TRACK)
            log('buttons: the model of SHOW TEAMS against the stock button: %.1f%% of the ink off' % (100 * share(model, stock)))
    return [(BUTTON_FILE, 0, 0, 0, BUTTON_W, BUTTON_H, '', mask(BUTTON_TEXT, BUTTON_W, BUTTON_H, BUTTON_W / 2.0 - 0.5, BUTTON_BASE))]


def tab(_game, log):
    x, y, w, h = TAB_BOX
    log('tabmenu: %s over TAB' % TAB_TEXT)
    return [(TAB_FILE, 0, x, y, w, h, '', mask(TAB_TEXT, w, h, (10 + 33) / 2.0 - x, TAB_BASE))]


PROMPTS = (('padtitle', title), ('padattract', attract), ('padprompts', records), ('padgallery', gallery_all), ('padoptions', options_all),
           ('lobby', buttons), ('tabmenu', tab))
HINTS = 'devices'                         # the devices page's hint lines, HINT_ART


def make(game, log=print):
    art = {key: maker(game, log) for key, maker in PROMPTS}
    art[HINTS] = hints(game, log)
    return art


def packed(blits):
    lines = []
    for file, sheet_, x, y, w, h, variant, texels in blits:
        b64 = base64.b64encode(zlib.compress(struct.pack('<%dH' % len(texels), *texels), 9)).decode('ascii')
        chunks = ["'%s'" % b64[i:i + 96] for i in range(0, len(b64), 96)]
        lines.append("        ('%s', %d, %d, %d, %d, %d, '%s',\n         " % (file, sheet_, x, y, w, h, variant) + '\n         '.join(chunks) + '),\n')
    return lines


def generated(art):
    lines = [BEGIN, '# The pad\'s prompts: key -> ((file, sheet, x, y, width, height, variant, texels), ...),\n',
             '# the file under BINDATA\\\\MISC, the variant \'\' for every release or the language\n',
             '# of the file it goes with, the texels 16-bit and zlib-compressed; see\n',
             '# tools/prompts.py.\n', 'PROMPT_ART = {\n']
    for key, _maker in PROMPTS:
        lines += ["    '%s': (\n" % key] + packed(art[key]) + ['    ),\n']
    lines += ['}\n', '# The Device Settings page\'s hint lines, the same way: each line\'s two\n',
              '# halves, strips for the sheet the patcher appends to OPTIONS.TXR.\n', 'HINT_ART = (\n']
    lines += [line.replace('        (', '    (', 1).replace('\n         ', '\n     ') for line in packed(art[HINTS])]
    lines += [')\n', END]
    return ''.join(lines)


def carried(region):
    """The art the script carries: the generated region run as Python."""
    ns = {}
    exec(region, ns)

    def unpacked(blits):
        out = []
        for file, sheet_, x, y, w, h, variant, b64 in blits:
            raw = zlib.decompress(base64.b64decode(b64))
            out.append((file, sheet_, x, y, w, h, variant, list(struct.unpack('<%dH' % (len(raw) // 2), raw))))
        return out
    out = {key: unpacked(blits) for key, blits in ns['PROMPT_ART'].items()}
    out[HINTS] = unpacked(ns.get('HINT_ART', ()))
    return out


# A font rasterises a little differently from one FreeType or font build
# to the next, so the check does not ask for the baked texels: a render
# is the same art when the blits sit where the baked ones do, at most
# FAR_TOLERANCE of a blit's texels are more than one level of 15 apart
# in any channel, and none is more than FAR levels apart.
FAR_TOLERANCE, FAR = 0.02, 3


def compare(baked, made):
    """What sets two sets of art apart, or '' when nothing does, and
    whether they are the same texel for texel."""
    same = True
    for key in [key for key, _maker in PROMPTS] + [HINTS]:
        a, b = baked.get(key, ()), made[key]
        if [blit[:7] for blit in a] != [blit[:7] for blit in b]:
            return '%s: the blits are not where the baked ones are' % key, False
        for (_f, sheet_, x, y, _w, _h, _v, old), (_f2, _s, _x, _y, _w2, _h2, _v2, new) in zip(a, b):
            apart = [levels(p, q) for p, q in zip(old, new)]
            same = same and not any(apart)
            if max(apart) > FAR or sum(d > 1 for d in apart) > FAR_TOLERANCE * len(apart):
                return '%s, sheet %d at (%d, %d): %d texels more than a level apart, the furthest %d' % (
                    key, sheet_, x, y, sum(d > 1 for d in apart), max(apart)), False
    return '', same


def write_pngs(art, game, folder):
    """Each touched sheet as it will be, over grey, four times the size;
    an appended sheet on its own."""
    from PIL import Image
    os.makedirs(folder, exist_ok=True)
    for key, blits in art.items():
        for (file, index) in dict.fromkeys((b[0], b[1]) for b in blits):
            mine = [b for b in blits if (b[0], b[1]) == (file, index)]
            if not file.lower().endswith('.txr'):           # a bitmap's mask: the coverage over grey
                for _f, _s, x, y, w, h, _v, new in mine:
                    im = Image.new('L', (w, h))
                    im.putdata([255 - (t >> 12) * 13 for t in new])
                    im.resize((w * 4, h * 4), Image.NEAREST).save(os.path.join(folder, '%s-%s.png' % (key, file)))
                continue
            if index < sheet_count(game, file):
                fmt, width, texels = sheet(game, file, index)
            else:
                fmt, width, texels = 8, 256, [0x0fff] * (256 * 256)
            for _f, _s, x, y, w, h, _v, new in mine:
                for dy in range(h):
                    texels[(y + dy) * width + x:(y + dy) * width + x + w] = new[dy * w:(dy + 1) * w]
            im = Image.new('RGB', (width, len(texels) // width))
            if fmt == 8:
                im.putdata([tuple((60 * (15 - (t >> 12)) + (t >> s & 15) * 17 * (t >> 12)) // 15 for s in (8, 4, 0)) for t in texels])
            elif fmt == 2:
                im.putdata([tuple((t >> s & 31) * 8 for s in (10, 5, 0)) if t >> 15 else (60, 60, 60) for t in texels])
            else:
                im.putdata([((t >> 11) * 8, (t >> 5 & 63) * 4, (t & 31) * 8) for t in texels])
            top = max(0, min(b[3] for b in mine) - 40)
            im = im.crop((0, top, width, min(im.height, max(b[3] + b[5] for b in mine) + 8)))
            im.resize((im.width * 4, im.height * 4), Image.NEAREST).save(os.path.join(folder, '%s-%s-%d.png' % (key, file.split('.')[0], index)))


def main(argv):
    args = argv[1:]
    check = '--check' in args
    show = None
    if '--show' in args:
        show = args[args.index('--show') + 1]
        args.remove(show)
    args = [a for a in args if not a.startswith('--')]
    if len(args) > 1 or (show and not args):
        print(__doc__.strip())
        return 2
    game = args[0] if args else None
    with open(TARGET, encoding='utf-8') as fh:
        text = fh.read()
    pattern = re.compile(re.escape(BEGIN) + '.*?' + re.escape(END), re.S)
    if not pattern.search(text):
        raise SystemExit('no prompts region in sr2-patcher.py')
    try:
        art = make(game, print if game or not check else (lambda _line: None))
    except (ImportError, SystemExit) as exc:
        if check and (isinstance(exc, ImportError) or 'not found' in str(exc)):
            print('prompts: skipped (%s)' % exc)
            return SKIPPED
        raise
    if show:
        write_pngs(art, game, show)
    if check:
        why, same = compare(carried(pattern.search(text).group(0)), art)
        if why:
            print('prompts differ: %s; run tools/prompts.py on the machine the art comes from' % why)
            return 1
        print('prompts match' if same else 'note: prompts match within the rasteriser\'s tolerance')
        return 0
    new = generated(art)
    text = pattern.sub(lambda _m: new, text)
    with open(TARGET, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(text)
    print('wrote %d prompt(s) into sr2-patcher.py' % len(art))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
