#!/usr/bin/env python3
"""Compile net/ into net/MGNetWk.dll and record its hashes in
../sr2-patcher.py, or check that the two still agree.

    python3 net/build.py            # compile and write
    python3 net/build.py --check    # verify only, writes nothing
    python3 net/build.py --out DIR  # also drop MGNetWk.dll in DIR, to try
    python3 net/build.py --out DIR --dry   # only that: nothing written to the repository

The DLL is a file in the repository: the patcher reads it from net/ or
from beside itself and checks it against MGNETWK_SHA before installing
it. --check compares the sources' hash with the recorded one rather than
rebuilding - two mingw versions do not make identical bytes from
identical C - and the DLL on disk against its recorded hash.
"""
import hashlib
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TARGET = os.path.join(ROOT, 'sr2-patcher.py')
DLL = os.path.join(HERE, 'MGNetWk.dll')
SOURCES = ('sr2net.h', 'sock.h', 'sr2net.c', 'com.c', 'mgnetwk.def')
CC = 'i686-w64-mingw32-gcc'
IMAGE_BASE = 0x6c560000             # pinned, with no timestamp, so a rebuild is the same bytes
EXPORTS = (b'DllGetClassObject', b'DllCanUnloadNow', b'DllRegisterServer', b'DllUnregisterServer',
           b'_CreateGameNetwork@4')

BEGIN = '# --- GENERATED by net/build.py: BEGIN (do not edit) ---\n'
END = '# --- GENERATED by net/build.py: END ---\n'


FLAGS = ('-O2', '-s', '-shared', '-Wall', '-Wextra', '-lws2_32', '-Wl,--enable-stdcall-fixup',
         '-Wl,--no-insert-timestamp', '-Wl,--image-base=%#x' % IMAGE_BASE)


def source_hash():
    """The sources and the flags: a change to either is a rebuild."""
    h = hashlib.sha256()
    for name in SOURCES:
        with open(os.path.join(HERE, name), 'rb') as fh:
            h.update(name.encode() + b'\0' + fh.read() + b'\0')
    h.update(' '.join(FLAGS).encode())
    return h.hexdigest()


def compile_dll(workdir):
    if not shutil.which(CC):
        raise SystemExit('%s not found; install gcc-mingw-w64-i686' % CC)
    out = os.path.join(workdir, 'MGNetWk.dll')
    cmd = [CC, '-I', HERE, '-o', out,
           os.path.join(HERE, 'com.c'), os.path.join(HERE, 'sr2net.c'), os.path.join(HERE, 'mgnetwk.def'),
           *FLAGS]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode:
        sys.stderr.write(proc.stderr)
        raise SystemExit('compile failed')
    if proc.stderr.strip():
        sys.stderr.write(proc.stderr)
    with open(out, 'rb') as fh:
        blob = fh.read()
    if blob[:2] != b'MZ':
        raise SystemExit('not a PE file')
    for name in EXPORTS:
        if name not in blob:
            raise SystemExit('export missing: %s' % name.decode())
    return blob


def generated(blob, sha):
    return (BEGIN
            + "# MUSASHI\\MGNetWk.dll, built from net/ and carried beside the patcher\n"
              "# rather than inside it; MGNETWK_SRC the sources' hash, MGNETWK_SHA the\n"
              "# file's.\n"
            + "MGNETWK_SRC = '%s'\n" % sha
            + "MGNETWK_SHA = '%s'\n" % hashlib.sha256(blob).hexdigest()
            + END)


def main(argv):
    check = '--check' in argv
    with open(TARGET, encoding='utf-8') as fh:
        text = fh.read()
    pattern = re.compile(re.escape(BEGIN) + '.*?' + re.escape(END), re.S)
    if not pattern.search(text):
        raise SystemExit('no net region in sr2-patcher.py')
    sha = source_hash()
    if check:
        hit = re.search(r"^MGNETWK_SRC = '([0-9a-f]+)'", text, re.M)
        if not hit or hit.group(1) != sha:
            print('net/ differs from the build in sr2-patcher.py: run net/build.py')
            return 1
        want = re.search(r"^MGNETWK_SHA = '([0-9a-f]+)'", text, re.M)
        try:
            with open(DLL, 'rb') as fh:
                got = hashlib.sha256(fh.read()).hexdigest()
        except OSError:
            print('net/MGNetWk.dll is missing: run net/build.py')
            return 1
        if not want or want.group(1) != got:
            print('net/MGNetWk.dll is not the one sr2-patcher.py expects: run net/build.py')
            return 1
        print('MGNetWk.dll matches net/ (%s)' % sha[:12])
        return 0
    with tempfile.TemporaryDirectory() as workdir:
        blob = compile_dll(workdir)
    if '--out' in argv:
        if argv.index('--out') + 1 >= len(argv):
            raise SystemExit('--out needs a directory')
        with open(os.path.join(argv[argv.index('--out') + 1], 'MGNetWk.dll'), 'wb') as fh:
            fh.write(blob)
    if '--dry' in argv:
        print('compiled MGNetWk.dll, %d bytes' % len(blob))
        return 0
    with open(DLL, 'wb') as fh:
        fh.write(blob)
    text = pattern.sub(lambda _m: generated(blob, sha), text)
    with open(TARGET, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(text)
    print('wrote net/MGNetWk.dll, %d bytes, and its hashes into sr2-patcher.py (%s)'
          % (len(blob), sha[:12]))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
